### ISSUE TITLE
Add arguments to file listing

### ISSUE THREAD

**Issue by TaijaQ** [TaijaQ/Nitbit#4]
Method: `files.list`

Fetches a list of a team's files, including snippets, Google Docs and more. 

### TODO
- [ ] Filter by user
- [ ] Filter by channel id
- [ ] Get files from a certain timeperiod
- [ ] Filter by type
